### ISSUE TITLE
command - Snippets: Select snippet don't work on LT 0.8.0-alpha

### ISSUE THREAD

**Issue by Trapets** [rundis/lt-snippets#22]
Hei!

LT 0.8.0-alpha on Manjaro 15.09 linux machine.
Can't insert snippet from command pane.

LT console error log:
Invalid behavior: :lt.objs.sidebar.command/select!

TypeError: [cljs.core.str(...)].join(...).contains is not a function
    at eval (/home/trapets/.config/LightTable/plugins/Snippets/snippets_compiled.js:530:108)
    at file:///opt/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:7913:33
    at cljs.core.LazySeq.sval (file:///opt/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:5561:40)
    at cljs.core.LazySeq.cljs$core$ISeqable$_seq$arity$1 (file:///opt/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:5571:8)
    at cljs.core._seq (file:///opt/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:2311:14)
    at cljs.core.seq (file:///opt/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:2824:27)
    at file:///opt/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:7600:29
    at cljs.core.LazySeq.sval (file:///opt/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:5561:40)
    at cljs.core.LazySeq.cljs$core$ISeqable$_seq$arity$1 (file:///opt/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:5571:8)
    at cljs.core._seq (file:///opt/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:2311:14)
    at cljs.core.seq (file:///opt/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:2824:27)

**Comment by rundis** [comment]
Yeah electron doesn't seem to support JavaScript String.contains.
 Would you be willing to submit a pullrequest (basically replace (.contains... with something like (> (.indexOf someStr) -1) ? 

Otherwise I'll try to get to it at some point not to far away ...
Cheers !

**Comment by rundis** [comment]
This should be fixed with version 0.1.1

**Comment by Trapets** [comment]
Thanks, it works now.
